# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: 
      - main
      - release
      - test_auto_release
    
  pull_request:
    branches:
      - main
      - release
      - test_auto_release

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
        cache: maven

    - name: Build and test project with Maven
      run: mvn -B package --file pom.xml
      
  publish-job:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/test_auto_release'
    steps:
    - name: deploy
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven


    - run: mvn -B package --file pom.xml -DskipTests
    
    - name: Get version
      run: |
        VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
        echo "::set-output name=version::$VERSION"
      id: get_version
    
    - run: echo ${{ steps.get_version.outputs.version}}
    
    
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        # GitHub secret token
        repo_token: "${{ secrets.PAT }}"
        # Git tag (for automatic releases)
        automatic_release_tag: "v${{steps.get_version.outputs.version}}.${{github.run_number}}"

        # Should this release be marked as a pre-release?
        prerelease: false # optional, default is true
        # Release title (for automatic releases)
        title: "Release ${{steps.get_version.outputs.version}}.${{github.run_number}}" # optional
        # Assets to upload to the release
        files: |
          target/*jar-with-dependencies.jar
          database/database.db



